name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Apply Terraform to dev and prod
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    strategy:
      matrix:
        env: [dev, prod]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: environments/${{ matrix.env }}
        run: terraform init

      - name: Select or Create Workspace
        working-directory: environments/${{ matrix.env }}
        run: |
          terraform workspace select ${{ matrix.env }} || terraform workspace new ${{ matrix.env }}

      - name: Terraform Apply
        working-directory: environments/${{ matrix.env }}
        run: terraform apply -auto-approve